### ISSUE TITLE
Gemspec missing file pin_values.rb

### ISSUE THREAD

**Issue by JSchaenzle** [jwhitehorn/pi_piper#23]
The gemspec file is missing pin_values.rb which causes an error when you try to `require 'pi_piper'`. I was really confused why your spec tests were passing at first. Looks like it's because Travis just pulls down the repo and runs the tests and doesn't use the gemspec file at all I think. I have never set up Travis before but I bet there is a way to get it to use your gemspec file. I would recommend looking into that.

**Comment by v0dro** [comment]
I have fixed this in #34
