### ISSUE TITLE
No such file or directory - /sys/class/gpio/gpio4/direction

### ISSUE THREAD

**Issue by raldred** [jwhitehorn/pi_piper#28]
Hey,
Sorry If this is noob issue, I couldn't see anything in the README.
I've Got a tiny script which loops and prints the output of a pin.
    
    pin = PiPiper::Pin.new(pin: 4, direction: :in, pull: :up)
    puts pin.read

I get the following error upon running the script.

    $ sudo ruby read_sensor.rb 
    /var/lib/gems/1.9.1/gems/pi_piper-1.3.2/lib/pi_piper/pin.rb:24:in `initialize': No such file or directory - /sys/class/gpio/gpio4/direction
    from /var/lib/gems/1.9.1/gems/pi_piper-1.3.2/lib/pi_piper/pin.rb:24:in `open'
    from /var/lib/gems/1.9.1/gems/pi_piper-1.3.2/lib/pi_piper/pin.rb:24:in `initialize'

I can get the output of my device by echoing /sys/bus/w1/devices/devicenumber/w1_slave

**Comment by elmatou** [comment]
PiPiper is not intended to read 1-wire bus, but only raw GPIO state. I'm working on a ruby implementation of 1-wire, I'll keep you up to date.

**Comment by raldred** [comment]
Ahh, I see, I didn't realise. Please do :) Thanks
