### ISSUE TITLE
Increase EventMachine dependency version to 1.0.7

### ISSUE THREAD

**Issue by v0dro** [jwhitehorn/pi_piper#33]
I'm facing some problems with building EventMachine 1.0.3 native extensions (a possible fix is given [here](http://stackoverflow.com/questions/17361958/eventmachine-gem-install-fail). 

Increasing the version to 1.0.7 (latest) fixes the issue.

**Comment by v0dro** [comment]
And I think this issue arises only on ruby 2.2.0

**Comment by jwhitehorn** [comment]
My schedule doesn't give me enough time to really work on this project at the moment, but I'd gladly accept a pull request.

**Comment by v0dro** [comment]
Sure thing!

Also could you tell me if there is anything specific that I should keep in mind during testing?

**Comment by elmatou** [comment]
Same here, happend only with ruby 2.2.x . Eventmachine 1.0.4 (a later) fix this.

**Comment by elmatou** [comment]
EventMachine dependency could be withdrawn. 
It is only used for PiPiper#spi_poll which could be done with a simple sleep in a loop. Other Implementations, with EventMachine, Celluloid, Cool.io, Thread, Fiber.... should be done in application code.

**Comment by zsyed91** [comment]
I agree with @elmatou. If we can move this into the actual app code then it should reduce complexity of the gem. But anyhow, the current changes going into `1.9.9` which hopefully should be released in the next day or so contains the latest version of `EventMachine`. So this issue should be resolved once that is released. I am going to go ahead and close this.
