### ISSUE TITLE
PWM? how to make a buzzer sound?

### ISSUE THREAD

**Issue by joecabezas** [jwhitehorn/pi_piper#44]
Hello, I want to make a piezo buzzer sound, there is a way to do this?, is pi_piper able to pwm?, thanks

**Comment by elmatou** [comment]
not the released gem, nor the develop branch. But their is two forks with this implementation : 
* mine using only the bcm library : https://github.com/elmatou/pi_piper
* another relying on piblaster, a binary allowing PWM software or hardware

**Comment by joecabezas** [comment]
thanks, how to install your library?

**Comment by elmatou** [comment]
not particularly a pi_piper question, use bundler ?

gem 'nokogiri', :git => 'https://github.com/tenderlove/nokogiri.git'


just change je the gem name and the github url.

**Comment by elmatou** [comment]
As of today PWM develop branch support Hardware PWM in pin 18.
if everything is ok please close the issue

**Comment by joecabezas** [comment]
Thanks everyone for making the community awesome <3, I am closing this
