### ISSUE TITLE
Gem Version 2.0?

### ISSUE THREAD

**Issue by ghost** [jwhitehorn/pi_piper#73]
## Help

I have been trying to install this gem on ruby 1.9.3 but it says that the gem is for ruby gem version 2.0.

Does anyone have any idea on how to fix this?

**## Thank You**

**Comment by zsyed91** [comment]
Can you give a dump of the error? I suspect you need to upgrade your `gem`. Try the first answer here: [how-to-upgrade-rubygems](http://stackoverflow.com/questions/13626143/how-to-upgrade-rubygems)

Alternatively try

``` shell
gem update --system
```
